### ISSUE TITLE
Emoji not rendered properly

### ISSUE THREAD

**Issue by Vasallius** [bennyxguo/Obsidian-Obsidianite#19]
Attached below is a sample of the problem. I did not experience this before but for some reason, today it is consistently not rendering emoji when i'm linking to a note that starts with an emoji. However, upon linking, the emoji gets resolved, must be a bug.

![image](https://user-images.githubusercontent.com/64886200/102004574-d6791380-3d4c-11eb-96f7-08924360de35.png)

**Comment by TriDiamond** [comment]
Can you provide the emoji that you used? @Vasallius

**Comment by Vasallius** [comment]
🌱 🌳 and 🌲 mostly @TriDiamond

**Comment by TriDiamond** [comment]
> 🌱 🌳 and 🌲 mostly @TriDiamond

Alrighty I will test them out.

**Comment by TriDiamond** [comment]
@Vasallius I couldn't reproduce this on my end, could this be caused by certain font you are using? Are you using the font the theme suggested?

![image](https://user-images.githubusercontent.com/24708758/103448340-59014d00-4cd3-11eb-8bc3-bd28202091ef.png)

**Comment by krokofant** [comment]
Could not reproduce on Windows without the recommended fonts installed.

**Comment by bennyxguo** [comment]
Yeah I will close this for now. But feel free to raise a ticket again if the problem continues. Make sure you provide more details thanks!
