### ISSUE TITLE
Theme resets when switching files

### ISSUE THREAD

**Issue by psyguy** [bennyxguo/Obsidian-Obsidianite#24]
Hey there,

Thanks for this gorgeous theme! I really want to start using it but I have a problem.

When I activate the theme, the appearance changes to this:

![image](https://user-images.githubusercontent.com/8527082/105560210-7c884800-5d13-11eb-9edc-498fdb6d8893.png)

Though, when I click on the file to become my focus/active pane, the theme kind of resets:

![image](https://user-images.githubusercontent.com/8527082/105560212-7e520b80-5d13-11eb-9223-ccbd2b12e982.png)

I am on Obsidian 0.10.8 and use Andy Mustang sliding panes plugin.

Cheers!

---
## Update:

I though it could be (partially) due to the manually added snippets to `obsidian.css` (as the previous costume theme was installed with some manual mending). I removed the file (so restored to default) but the issue persists.

**Comment by krokofant** [comment]
I cannot reproduce this. If it's still an problem the bump this issue.
