### ISSUE TITLE
Codeblock indent error

### ISSUE THREAD

**Issue by raawaa** [bennyxguo/Obsidian-Obsidianite#28]
Codeblock indent incorrectly in editor mode. 

Fix the problem myself by commenting out this line below😋:

https://github.com/TriDiamond/Obsidian-Obsidianite/blob/2f69bdcc45920d5b9e3c5bc36d95ffdb6edff72c/obsidian.css#L1094

before fixing ⬇
![before](https://user-images.githubusercontent.com/8319722/112690122-3cca1200-8eb6-11eb-8249-3b74cf9926f1.png)

after fixing ⬇
![image](https://user-images.githubusercontent.com/8319722/112690496-d2fe3800-8eb6-11eb-83d3-9fb6b04522e1.png)

**Comment by TriDiamond** [comment]
Got it, I will make a change in next version.

**Comment by pepastach** [comment]
Thank you for the fix. This was driving me (as a developer) crazy :)

**Comment by bennyxguo** [comment]
Fixed this on the latest commit. Thanks @raawaa for the tips!
