### ISSUE TITLE
[ characters are hard to view in text editor mode

### ISSUE THREAD

**Issue by tekwizz123** [bennyxguo/Obsidian-Obsidianite#29]
Currently the `[` characters are very hard to see when using the text editor mode and the only way I can really see the difference is the fact that links have a blue underline. Is there any way these highlights could use a slightly different color that stands out a bit more? Its easy for the eyes to loose track of these characters given how much they blend into the background.

**Comment by TriDiamond** [comment]
Ok, I will check on this one. Thanks for your issue.

**Comment by krokofant** [comment]
Alternatively could `[` & `]` (`.cm-s-obsidian span.cm-formatting-link`) have the same opacity as the url (`.cm-url`)?

Currently the square brackets have the same color but 0.25 opacity compared to the url opacity of 0.4.

Before and after:
![image](https://user-images.githubusercontent.com/5908498/135754075-97c92699-3ba5-4082-8731-6eef776a892d.png)
![image](https://user-images.githubusercontent.com/5908498/135754100-069be8a8-77a1-48cc-8ccd-0f0609e031d4.png)
---

Alternative 2, I kind of like this use of monospace font for the square brackets.
Before and after adding `font-family: var(--font-monospace);`:
![image](https://user-images.githubusercontent.com/5908498/135754438-ee29c280-cd00-4b7f-b982-5bd8b3131175.png)
![image](https://user-images.githubusercontent.com/5908498/135754434-518ecfdb-9058-43f3-8338-83ffddd35a8f.png)

**Comment by krokofant** [comment]
This issue doesn't seem as bad in the new live preview editor, in part since the markdown is only visible when you highlight a link.

I'll close this but if you still find it annoying bump this issue.
