### ISSUE TITLE
Scrolling in edit mode and Jumping up and down in preview mode

### ISSUE THREAD

**Issue by jiangaq** [bennyxguo/Obsidian-Obsidianite#31]
When I scroll through the blockquote part in the EDIT mode, the counterpart in preview mode will sometimes jumping up and down, normally will navigate to top of the document and then go back to the position where it should be.

Actually not just only your theme happened like that, same situation as blue topaz and minimal theme, maybe it's the bug of obsidian. 

I try to remove `position: relative` in `.markdown-preview-view blockquote` and `ul ul, .cm-s-obsidian pre.HyperMD-list-line`
it works. But I don't know if there will be any problem if I removed these code lines. 

Could you please explain why that happened? Is my solution correct?  Thank you!

**Comment by krokofant** [comment]
Can't reproduce this. If it still persists please provide a video and/or some markdown that it can be reproduced with.
