### ISSUE TITLE
Indent overlapping in preview mode

### ISSUE THREAD

**Issue by xidlegend** [bennyxguo/Obsidian-Obsidianite#33]
![image](https://user-images.githubusercontent.com/26184016/126112168-3145d2c4-e945-4f8d-9205-6e32477de895.png)

This is pretty much it 🤷

**Comment by krokofant** [comment]
I see two issues in the preview
1. The folding arrows are not aligned the same horizontally
2. The checkboxes are rendered wrongly when they have no text to the right

This breaks the checkboxes (2) like in your preview:
```markdown
### Foo
- Watch this
	- [ ]  
- Watch that
	- [ ] 

```
While this works:
```markdown
### Foo
- Watch this
	- [ ]  f
- Watch that
	- [ ] 

```
