### ISSUE TITLE
图片居中能否优化

### ISSUE THREAD

**Issue by kehehee1** [bennyxguo/Obsidian-Obsidianite#34]
图片居中效果很好，但有些图片是在段落内的，这些图片也被居中了，和预想的就不太一样了，如下图所示
![image](https://user-images.githubusercontent.com/4415195/127951659-6e677ab5-2c9d-4d9c-b022-3dcd4961810c.png)
使用默认主题则显示正常如下
![image](https://user-images.githubusercontent.com/4415195/127951750-08149ce1-b63b-498f-a6bb-85c9af5fe877.png)
不知道有没有好的解决办法

**Comment by bennyxguo** [comment]
最新版本把图片向左对齐了，图片剧中可以用 HTML 代码来实现，这样会更加便利。
