### ISSUE TITLE
Adding code block hides chunks of non-link text in edit mode iOS

### ISSUE THREAD

**Issue by sofie-bird** [bennyxguo/Obsidian-Obsidianite#41]
Absolutely love this theme, thanks so much for your work on it.

In edit mode, on files with code blocks (even empty code blocks), there will be a large blank box (similar in style to the code box, but wider, and clipped over text) covering an area of the note. Only text inside links will appear "through" the box. Block typically appears at the top of the page, and appears in the same place on each device. (folding and unfolding a nearby area can give you a brief view of the text, but as soon as you start typing it disappears again). Issue persists with all community plugins turned off.

Issue repro'd across iPhone 12Pro running 14.8, iPad mini 2021 running 15.1, iPad Pro 2020 running 15.1.

Issue does not appear on Windows 10.

![Photo 5-12-21, 3 13 05 pm](https://user-images.githubusercontent.com/2244756/144733632-242b0a58-cd29-457c-8ada-8eeabeeaa8e7.png)
![Photo 5-12-21, 3 13 13 pm](https://user-images.githubusercontent.com/2244756/144733635-d8eea22b-cc16-4d8d-982e-636c24f02392.png)

**Comment by JustinB555** [comment]
Hey, noticed you had a similar problem to https://github.com/bennyxguo/Obsidian-Obsidianite/issues/44. Until there is a proper fix to the issue, maybe that will help you.

**Comment by krokofant** [comment]
I can't reproduce this now. I think this was fixed along with the above linked issue and the live preview updates.

Please bump this issue if it's still happening.
