### ISSUE TITLE
渲染出问题了

### ISSUE THREAD

**Issue by Immortal-Sty** [bennyxguo/Obsidian-Obsidianite#46]
我改了一点点，但这个问题在我改前和改后都有。

存在代码块时，编辑模式最前面几行无法显示（无论是所见即所得还是源码），但在预览模式下可以正常看见，如图所示：

![](https://gitee.com/immortalsty/img-utools/raw/master/img/2022.02.28_03.03.44%20(1)_2022.2.28_03:04:08_m3rpldg0xs.png)

![](https://gitee.com/immortalsty/img-utools/raw/master/img/2022.02.28_03.13.12_2022.2.28_03:13:19_e4s0yoep2b.png)

**Comment by bennyxguo** [comment]
duplicate #47
