### ISSUE TITLE
hope to get theme for plugin calander

### ISSUE THREAD

**Issue by hong-tm** [bennyxguo/Obsidian-Obsidianite#5]
![Snipaste_2020-11-08_00-00-16](https://user-images.githubusercontent.com/51999870/98445928-7e4f6000-2155-11eb-950c-2d9550014baf.png)

**Comment by TriDiamond** [comment]
@hong-tm Will definitely work on this!

**Comment by hong-tm** [comment]
@TriDiamond actually what is the function for the dot?

**Comment by TriDiamond** [comment]
> @TriDiamond actually what is the function for the dot?

I think it's the amount of daily note you made on that day. Not too sure, haven't checked out that theme myself.

**Comment by krokofant** [comment]
Right now there does not seem to be any theming issues with the calendar plugin.
![image](https://user-images.githubusercontent.com/5908498/194785884-a8df00d2-9995-4881-b1ef-2eef973f3988.png)
