### ISSUE TITLE
List bullets are duplicated (should take the new .list-bullet into account)

### ISSUE THREAD

**Issue by krokofant** [bennyxguo/Obsidian-Obsidianite#64]
![image](https://user-images.githubusercontent.com/5908498/195847702-43323c1d-ded2-488e-b325-8a6fe0b4f736.png)

I'm not sure which one that should be kept. Easy hack is to just set `display: none` on the `.list-bullet` but it's probably better to try and style the new `.list-bullet` instead of adding a custom one.

**Comment by krokofant** [comment]
Also an issue in presentation mode
![image](https://user-images.githubusercontent.com/5908498/198279131-fc2e575b-8d34-4ac1-a9d8-16efaf5ac281.png)

**Comment by bennyxguo** [comment]
This is fixed in the latest version, please update your theme thanks! ❤️
