### ISSUE TITLE
Check box location incorrect if it is in live preview mode and generated by Obsidian tasks plugin

### ISSUE THREAD

**Issue by yuiasora1024** [bennyxguo/Obsidian-Obsidianite#67]
As title mentioned. 

It is fine if I switch to the reading mode or if the tasks are not shown up by the query of this plugin. Fine if I use dataview plugin too. 
The actually clickable box located somewhere in-between the visual box and tasks.

**Comment by krokofant** [comment]
@yuiasora1024 Could you provide an example of this? Screenshots and markdown code to replicate the issue.

**Comment by yuiasora1024** [comment]
<img width="830" alt="螢幕截圖 2022-11-07 上午8 04 45" src="https://user-images.githubusercontent.com/92098962/200202889-c9641a1d-9a77-4a92-b0ce-2e924d029331.png">

I actually need to click the space in front of the task to check it off.

**Comment by krokofant** [comment]
There is a lot weird with the checkboxes in read mode, especially when the lists are indented:
![image](https://user-images.githubusercontent.com/5908498/200208289-5807fc55-a123-4fa9-ac2a-1a1a8f5fa13a.png)

Maybe the entire read mode code needs to be reviewed, but I don't know why one even uses the read mode after live edit came out. 🤔

**Comment by yuiasora1024** [comment]
It is not happens in read mode: if I switched to read mode everything is
fine.

But if I do it in live preview mode, it becomes weird.

「Emil Sundin ***@***.***>」在 2022年11月7日 週一，上午9:30 寫道：

**Comment by krokofant** [comment]
I can't reproduce this anymore. Now the clickable area around the checkbox is actually larger than the checkbox itself 😅 
![image](https://github.com/bennyxguo/Obsidian-Obsidianite/assets/5908498/ecfde7ac-ce67-4237-887b-5651bdea12a1)
