### ISSUE TITLE
Tag name is hard to read in editing mode

### ISSUE THREAD

**Issue by bicolino34** [bennyxguo/Obsidian-Obsidianite#68]
Tags are hard to read in editing mode.
I use dark theme and have live preview turned on. It looks the same if live preview is turned off
Tags in editing mode:
![image](https://user-images.githubusercontent.com/58372007/196750121-ec71a420-a7c1-4acc-97f3-557933299872.png)
Tags in view mode: 
![image](https://user-images.githubusercontent.com/58372007/196750212-f378dcee-05a0-4be5-a211-ca173adf5b21.png)

Obsidian version is 1.0.0
Theme is of the latest version, I just updated it.

**Comment by bicolino34** [comment]
For some reason, this problem disappeared. I don't think there has been any update.
Tags now look like that
![image](https://user-images.githubusercontent.com/58372007/196934474-ddd57d46-970d-48ab-bc58-b441263a73ca.png)

**Comment by bennyxguo** [comment]
@bicolino34 there are changes being made to the master branch lately, will tag a new version this weekend with all the updates.

**Comment by bennyxguo** [comment]
This is fixed in the latest version, please update your theme thanks! ❤️
