### ISSUE TITLE
Strange backtick line spacing appearence

### ISSUE THREAD

**Issue by euphonics** [bennyxguo/Obsidian-Obsidianite#72]
When 2 backticks are typed sequentially, the second backtick goes onto the next line. 

Expected behavior (as per default Obsidian themes )is to simply show the 2 backticks, one after the other.

Current apperance:

```
`
`
```

Expected appearance:

```
``
```

**Comment by bennyxguo** [comment]
@euphonics thanks for reporting the issue and thanks @krokofant for providing the fix. Merging it now!
