### ISSUE TITLE
Front Matter Display Issue?

### ISSUE THREAD

**Issue by salsysd** [bennyxguo/Obsidian-Obsidianite#79]
Hey @bennyxguo first off! thanks much for this theme! its been my main theme for quite some time now and I can't seem to move away! 
But I've updated today to the latest and noticed that the metadata / front matter is displayed twice in Reading View mode. 
See screenshot:

![image](https://user-images.githubusercontent.com/105071/200150486-18691615-33a7-40d6-9567-003e949c66d0.png)

Is this a bug? or ...

**Comment by krokofant** [comment]
@salsysd I cannot reproduce this
![image](https://user-images.githubusercontent.com/5908498/202213454-e401f7ee-bcbe-4148-a440-ab14e32a6cf5.png)

Obsidian has in it's own css set the frontmatter code section to `display: none` in read mode which means by default it should not show up.

I suggest you try to enable the restricted mode to disable all community plugins, in case there is some plugins that show this for you.

**Comment by krokofant** [comment]
You have the `Show frontmatter` option enabled in your settings. Disable and your issue goes away.
![image](https://user-images.githubusercontent.com/5908498/202911532-dc5c71bb-c8ed-45bd-ae47-6d761e984a0a.png)
