### ISSUE TITLE
Note Titles are displayed like normal body text

### ISSUE THREAD

**Issue by Do11-Master** [bennyxguo/Obsidian-Obsidianite#82]
I've checked the CSS, and it seems that the normal text in the body, is the same used in notes title. 

Not really sure if this is on purpose or not, but it makes it hard to see the title in reading mode.
It ironically displays correctly in editing mode, but that's a mode that no one reads anyway, aside from the author. 

![image](https://user-images.githubusercontent.com/68296772/212236285-95d9fcd3-e0b8-473c-9ce3-4e738fdda5b6.png)

**Comment by bennyxguo** [comment]
This is fixed in the latest version, please update your theme thanks! ❤️
