### ISSUE TITLE
Table border is nearly impossible to see in dark mode

### ISSUE THREAD

**Issue by fstlaneukraine** [bennyxguo/Obsidian-Obsidianite#87]
This is actually similar to #48  , but bringing it back up because it's still an issue.

I've tried to create a CSS snippet to take care of this but can't seem to figure out what property to target.

The table border is very dark in dark mode and is almost impossible to see. I'd like to make it white or the color of the headings.

Can this be done?

**Comment by bennyxguo** [comment]
Hey thanks for raising this ticket. I will look into it.

**Comment by fstlaneukraine** [comment]
> Hey thanks for raising this ticket. I will look into it.

Thank you! I love your theme above all others! New to Obsidian and it helps make it a joy to use.

**Comment by krokofant** [comment]
Is this better @fstlaneukraine ?
Before
![image](https://github.com/bennyxguo/Obsidian-Obsidianite/assets/5908498/cb940c98-27e5-400e-af52-c3f594a8fba9)

After
![image](https://github.com/bennyxguo/Obsidian-Obsidianite/assets/5908498/f21dc03f-3905-446b-ac3b-f764ce63f73d)

**Comment by fstlaneukraine** [comment]
> Is this better @fstlaneukraine ? Before ![image](https://user-images.githubusercontent.com/5908498/250361159-cb940c98-27e5-400e-af52-c3f594a8fba9.png)
> 
> After ![image](https://user-images.githubusercontent.com/5908498/250361184-f21dc03f-3905-446b-ac3b-f764ce63f73d.png)

I would be happy with that, yes. I would prefer slightly more but that would be an acceptable minimum if I was allowed to be picky :) .

**Comment by krokofant** [comment]
I created a PR for Benny to review. If you want to adjust this locally in your CSS snippets you can add the following, and adjust the `0.15` to a higher percentage to make it more visible.

```css
.theme-dark {
  --table-border-color: rgb(14, 210, 247, 0.15);
}
```

**Comment by fstlaneukraine** [comment]
> I created a PR for Benny to review. If you want to adjust this locally in your CSS snippets you can add the following, and adjust the `0.15` to a higher percentage to make it more visible.
> 
> ```css
> .theme-dark {
>   --table-border-color: rgb(14, 210, 247, 0.15);
> }
> ```

Worked perfectly. Thank you!
