### ISSUE TITLE
File tree issues after updating to 1.3.3/1.3.4

### ISSUE THREAD

**Issue by fstlaneukraine** [bennyxguo/Obsidian-Obsidianite#89]
1.3.3 and 1.3.4 have the same issue for me where if I click on a folder to expand or collapse, it moves/tabs the name of the folder to the right and it keeps doing that with each click. Went back to 1.2.8 and the issue is not present. This also happens with root folders where the folder won't move right, but the notes under it will.

After posting on the Obsidian Discord, it turns out this is due to the theme.

A recent update changed the padding for file trees so theme developers have to adapt the CSS to that.

I tested my 3 other custom themes as well as 'Default' and this issue does not occur with those themes and is specific to Obsidianite (at least from the themes I have installed).

I love your theme but with #87 and this issue, it's quickly becoming unusable. Please update your theme.

Thank you!

**Comment by Harvelon365** [comment]
I'm having the same issue!

**Comment by xion6** [comment]
Me too.

**Comment by ereymundopep** [comment]
to visualize the issues we are all having: 

![v1vf5mkr](https://github.com/bennyxguo/Obsidian-Obsidianite/assets/109108183/4964e605-3049-48d3-b80c-ef0b9f7d68ee)

**Comment by fstlaneukraine** [comment]
> to visualize the issues we are all having:
> 
> ![v1vf5mkr](https://user-images.githubusercontent.com/109108183/240984817-4964e605-3049-48d3-b80c-ef0b9f7d68ee.gif)

Thanks for doing that!

**Comment by jegathgreeny** [comment]
Requesting prompt resolution. Thanks!

**Comment by vladimir97mix** [comment]
Hi all!
To solve this problem, you can comment out the block indicated in the screenshot in the <your_workspace>\
\.obsidian\themes\Obsidianite\theme.css file
![theme](https://github.com/bennyxguo/Obsidian-Obsidianite/assets/62235606/93f19942-1b9b-4bca-8084-680084c78499)
V
![theme2](https://github.com/bennyxguo/Obsidian-Obsidianite/assets/62235606/bd9d261a-6256-4a18-bb22-2d29e81d8c72)

**Comment by ericlikedis** [comment]
good deal, this worked for me. thank you!

**Comment by jegathgreeny** [comment]
worked. thanks!

**Comment by fstlaneukraine** [comment]
Thank you for offering that fix. Confirmed working here as well.

**Comment by mayk78** [comment]
the css fix works indeed.. thank you.

**Comment by krokofant** [comment]
Fixed since v2.0.2 [916f219](https://github.com/bennyxguo/Obsidian-Obsidianite/commit/916f2195bb9c34d7df927e90927458e9d8fe9207)
