### ISSUE TITLE
Folders and files move to right unexpectly when reset accent color.

### ISSUE THREAD

**Issue by Greapi** [bennyxguo/Obsidian-Obsidianite#90]
**Description**: It is a strange a bug. When I click reset button in accent color setting, the folders and files in file explore will move to rigth.

**Reproduction**: You can click reset button in accent color setting repeatedly to reproduce this bug.

**Environment**: Windows 10, Obsidian 1.34, Obsidianite (Dark and Light Mode), no plugin.

![image](https://github.com/bennyxguo/Obsidian-Obsidianite/assets/51920111/bed0b1c2-6b1a-4289-9640-8f94741ca32b)

**Comment by ereymundopep** [comment]
Take a look at Issue #89, there is a work around for this.

**Comment by krokofant** [comment]
Fixed since v2.0.2 [916f219](https://github.com/bennyxguo/Obsidian-Obsidianite/commit/916f2195bb9c34d7df927e90927458e9d8fe9207)
